modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All Rights Reserved"
[[mods]]
modId="tastytiles"
version="1.2.0"
displayName="Tasty Tiles"
authors="Micomi"
displayTest="MATCH_VERSION"

description='''Tasty Tiles adds a yummy variety of building blocks focused around, well, tiles! Give your home some cozy ceramic flavor!'''

[[dependencies.tastytiles]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="AFTER"
side="BOTH"